baseURL = "https://vector.dev/"
languageCode = "en-us"
title = "Vector: A High-Performance Logs, Events, & Metrics Router"
theme = "vector"

[params]
  administrationURL = "https://docs.vector.dev/usage/administration"
  agentRoleURL = "https://docs.vector.dev/setup/deployment/roles/agent"
  backupsURL = "https://docs.vector.dev/use-cases/backups"
  chatURL = "https://chat.vector.dev"
  comparisonsURL = "https://docs.vector.dev/comparisons"
  conceptsURL = "https://docs.vector.dev/about/concepts"
  configurationURL = "https://docs.vector.dev/usage/configuration"
  correctnessURL = "https://docs.vector.dev/comparisons/correctness"
  costURL = "https://docs.vector.dev/use-cases/cost"
  cwLogsSinkURL = "https://docs.vector.dev/usage/configuration/sinks/aws_cloudwatch_logs"
  deploymentURL = "https://docs.vector.dev/setup/deployment"
  docsURL = "https://docs.vector.dev/"
  downloadURL = "https://github.com/timberio/vector/releases"
  elasticsearchSinkURL = "https://docs.vector.dev/usage/configuration/sinks/elasticsearch"
  fileSourceURL = "https://docs.vector.dev/usage/configuration/sources/file"
  forumURL = "https://forum.vector.dev"
  getStartedURL = "https://docs.vector.dev/setup/getting-started"
  governanceURL = "https://docs.vector.dev/use-cases/governance"
  guaranteesURL = "https://docs.vector.dev/about/guarantees"
  guidesURL = "https://docs.vector.dev/usage/guides"
  httpSinkURL = "https://docs.vector.dev/usage/configuration/sinks/http"
  installURL = "https://docs.vector.dev/setup/installation"
  issuesURL = "https://github.com/timberio/vector/issues"
  kafkaSinkURL = "https://docs.vector.dev/usage/configuration/sinks/kafka"
  lockinURL = "https://docs.vector.dev/use-cases/lock-in"
  logsToMetricsURL = "https://docs.vector.dev/usage/configuration/transforms/log_to_metric"
  luaURL = "https://docs.vector.dev/usage/configuration/transforms/lua"
  multiCloudURL = "https://docs.vector.dev/use-cases/multi-cloud"
  performanceURL = "https://docs.vector.dev/comparisons/performance"
  prometheusSinkURL = "https://docs.vector.dev/usage/configuration/sinks/prometheus"
  repoURL = "https://github.com/timberio/vector"
  roadmapURL = "https://github.com/timberio/vector/milestones?direction=asc&sort=title&state=open"
  s3SinkURL = "https://docs.vector.dev/usage/configuration/sinks/s3"
  securityURL = "https://docs.vector.dev/use-cases/security"
  serviceRoleURL = "https://docs.vector.dev/setup/deployment/roles/service"
  sinksURL = "https://docs.vector.dev/usage/configuration/sinks"
  sourcesURL = "https://docs.vector.dev/usage/configuration/sources"
  splunkHECSinkURL = "https://docs.vector.dev/usage/configuration/sinks/splunk_hec"
  statsdSourceURL = "https://docs.vector.dev/usage/configuration/sources/statsd"
  stdinSourceURL = "https://docs.vector.dev/usage/configuration/sources/stdin"
  subscribeActionURL = "https://app.getvero.com/forms/a748ded7ce0da69e6042fa1e21042506"
  syslogSourceURL = "https://docs.vector.dev/usage/configuration/sources/syslog"
  tcpSinkURL = "https://docs.vector.dev/usage/configuration/sinks/tcp"
  tcpSourceURL = "https://docs.vector.dev/usage/configuration/sources/tcp"
  topologiesURL = "https://docs.vector.dev/setup/deployment/topologies"
  transformsURL = "https://docs.vector.dev/usage/configuration/transforms"
  usecasesURL = "https://docs.vector.dev/use-cases"